CompileFlags:
  Add :
    - -std=c23
    - -Wall
    - -Wshadow
    - -Wconversion
    - -pedantic

Diagnostics:
  UnusedInclused: Strict

  ClangTidy:
    Add:
      - bugprone-*
      - readability-*
      - cert-*
      - misc-*
    Remove:
      - cppcoreguidelines
      - readability-identifier-naming

Completion:
  AllScopes: true

Index:
  Background: build

InlayHints:
  Enabled: true
  ParameterNames : true
  DeducedTypes: true
  Designators: true

Hover:
  ShowAKA: true
