theme = "kanagawa-dragon"

[editor]
line-number = "relative"
mouse = false
text-width = 100
continue-comments = false
bufferline = "multiple"
clipboard-provider = "termcode"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 25
